[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
param(
  [switch]$IncludeNodeModules,
  [switch]$IncludeVenv,
  [switch]$IncludeLogs
)

$ErrorActionPreference = 'Stop'

function Remove-PathSafe {
  param(
    [Parameter(Mandatory = $true)][string]$Path
  )

  if (-not (Test-Path -LiteralPath $Path)) {
    return
  }

  $fullPath = (Resolve-Path -LiteralPath $Path).Path

  if ($PSCmdlet.ShouldProcess($fullPath, 'Remove')) {
    try {
      Remove-Item -LiteralPath $fullPath -Force -Recurse -ErrorAction Stop
      Write-Host "Deleted: $fullPath"
      return
    } catch {
      # Some reserved Windows filenames (e.g. "nul") require extended-length paths.
    }

    $extended = "\\?\$fullPath"
    Remove-Item -LiteralPath $extended -Force -Recurse -ErrorAction Stop
    Write-Host "Deleted: $fullPath"
  }
}

function Remove-GlobSafe {
  param(
    [Parameter(Mandatory = $true)][string]$Glob,
    [string[]]$ExcludeLike = @()
  )

  $items = Get-ChildItem -Recurse -Force -ErrorAction SilentlyContinue -Path $PSScriptRoot\.. -Filter $Glob
  foreach ($item in $items) {
    $full = $item.FullName
    $skip = $false
    foreach ($pattern in $ExcludeLike) {
      if ($full -like $pattern) { $skip = $true; break }
    }
    if ($skip) { continue }
    Remove-PathSafe -Path $full
  }
}

Push-Location (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
try {
  # Build outputs / caches (safe to delete; regenerated by build/dev)
  Remove-PathSafe -Path 'client/dist'
  Remove-PathSafe -Path 'server/dist'
  Remove-PathSafe -Path 'mcp-bridge/dist'
  Remove-PathSafe -Path 'release'
  Remove-PathSafe -Path 'out'

  # TypeScript incremental build cache
  Remove-GlobSafe -Glob '*.tsbuildinfo' -ExcludeLike @('*\node_modules\*')

  # Python bytecode cache (outside venv)
  $pycaches = Get-ChildItem -Recurse -Directory -Force -ErrorAction SilentlyContinue -Path . -Filter '__pycache__' |
    Where-Object { $_.FullName -notmatch '\\venv\\' }
  foreach ($d in $pycaches) {
    Remove-PathSafe -Path $d.FullName
  }

  # Odd/accidental root file (Windows reserved name)
  Remove-PathSafe -Path 'nul'

  if ($IncludeLogs) {
    Remove-PathSafe -Path 'logs'
    Remove-PathSafe -Path 'carreralog'
  }

  if ($IncludeNodeModules) {
    Remove-PathSafe -Path 'node_modules'
  }

  if ($IncludeVenv) {
    Remove-PathSafe -Path 'venv'
  }
} finally {
  Pop-Location
}

